name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

env:
  CLICOLOR: 1

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run spell checker
        uses: crate-ci/typos@v1.29.10
        with:
          config: ./typos.toml
        env:
          RUST_BACKTRACE: 1
          CARGO_TERM_COLOR: always
